baseURL = "https://dizipal-insights.com"
languageCode = "en-us"
title = "DiziPal Phenomenon Analysis - Network Trends & Legal Alternatives"
theme = "ananke"

# SEO设置
enableRobotsTXT = true
canonifyURLs = true

# 分页设置
[pagination]
  pagerSize = 10

[params]
  # 网站描述，重要的SEO元素
  description = "Professional analysis of the DiziPal phenomenon, providing comprehensive network trend analysis and legal streaming platform recommendations. Discover the truth behind popular searches like DiziPal 1050, 1103, and more."
  
  # 作者信息
  author = "DiziPal Research Team"
  
  # 社交媒体
  twitter = "dizipal_insights"
  
  # 启用评论（可选）
  # comments = true
  
  # 网站图标
  favicon = "favicon.ico"
  
  # 首页横幅文本
  site_logo = ""
  
  # 自定义CSS
  custom_css = ["css/custom.css"]
  
  # Google Search Console verification
  google_site_verification = "google4b1fdf3d53df2686.html"

# 菜单配置
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
    
  [[menu.main]]
    name = "DiziPal Analysis"
    url = "/dizipal-analysis/"
    weight = 2
    
  [[menu.main]]
    name = "Legal Alternatives"
    url = "/legal-alternatives/"
    weight = 3
    
  [[menu.main]]
    name = "Trend Analysis"
    url = "/trends/"
    weight = 4
    
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 5

# 分类法
[taxonomies]
  category = "categories"
  tag = "tags"
  
# 输出格式
[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML"]
  section = ["HTML", "RSS"]

# SEO和站点地图
[sitemap]
  changefreq = "weekly"
  priority = 0.8
  filename = "sitemap.xml"

# 标记配置
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "github"
    lineNos = true

# 多语言支持（如需要）
  [languages]
    [languages.en-us]
      title = "DiziPal Phenomenon Analysis"
      weight = 1
      languageName = "English"